site_name: Antares Documentation
site_description: Open Source Laravel User Management Platform for standalone and SaaS applications. Based on Laravel, PHP7 ready, using flexible design patterns that keep the code clean and elegant.Speed up your work even up to 50% by using built-in workflow improvements.
site_url: http://antaresproject.io/docs
theme: null
theme_dir: 'layout'
site_favicon: favicon.png
markdown_extensions:
 - codehilite
 - smarty
 - toc:
    baselevel: '3'
use_directory_urls: false
pages:
 - Getting Started:
   - Introduction: index.md
   - Changelog: getting_started/changelog.md
   - Contribution Guide: getting_started/contributing.md
   - Issues Reporting Guide: getting_started/issues_reporting_guide.md
   - License: getting_started/license.md
 - Installation:
   - Requirements: installation/requirements.md
   - Automatic Installation Guide: installation/installation_auto.md 
   - Manual Installation Guide: installation/installation_manual.md
 - Antares Concepts:
   - Files structure: antares_concepts/core_&_files_structure.md
   - Modules: antares_concepts/components_&_modules.md
   - UI Structure: antares_concepts/ui_structure.md
   - Views: antares_concepts/views.md
 - Modules Development:
   - Migrations: modules_development/migrations.md
   - Service Providers: modules_development/service_providers.md
   - Routing: modules_development/routing.md
   - Controllers and Processors: modules_development/controllers_and_processors.md
   - ACL: modules_development/acl.md
   - Module Events: modules_development/module_events.md
   - Views and UI Components: modules_development/views_and_ui_components.md
 - Services:
   - Assets: services/assets.md
   - Auth & ACL: services/auth_and_acl.md
   - Breadcrumbs: services/breadcrumbs.md
   - Cryptor: services/cryptor.md
   - Datatables: services/datatables.md
   - Events: services/events.md
   - Filters: services/filters.md  
   - Formatters: services/formatters.md  
   - Form Builder: services/form_builder.md
   - Logs: services/logs.md  
   - Notifier: services/notifier.md  
   - Pagination: services/pagination.md  
   - Test benchmark: services/test_benchmark.md  
   - Translator: services/translator.md  
   - Twig: services/twig.md  
   - Validation: services/validation.md
   - Webpack: services/webpack.md  
   - Widget: services/widget.md  
 - Core modules:
   - Automation: core_modules/automation.md
   - Control: core_modules/control.md
   - Logger: core_modules/logger.md
   - Branding: core_modules/brands.md
   - Notifications: core_modules/notifications.md
   - Translations: core_modules/translations.md
   - Updater: core_modules/updater.md  
   - Widgets: core_modules/widgets.md
- Additional modules:
   - Search: modules/search.md
 - Tutorials:
   - Sample module: tutorials/sample_module.md
   - Sample widget template: tutorials/sample_widget_template.md


